// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthCheck: () => __TAURI_INVOKE<string>("health_check"),
	render: (input: string, output: string, scale: number | null, modelId: string | null, resize: number | null, outputResize: number | null, onProgress: Channel<RenderProgress>) => __TAURI_INVOKE<string>("render", { input, output, scale, modelId, resize, outputResize, onProgress }),
	importFolder: (dir: string) => __TAURI_INVOKE<string[]>("import_folder", { dir }),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	saveSettings: (settings: Settings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	listProjects: () => __TAURI_INVOKE<ProjectEntry[]>("list_projects"),
	createProject: (name: string) => __TAURI_INVOKE<string>("create_project", { name }),
	rememberProject: (path: string) => __TAURI_INVOKE<null>("remember_project", { path }),
	getFfmpegStatus: () => __TAURI_INVOKE<FfmpegInfo>("get_ffmpeg_status"),
	downloadFfmpeg: (onProgress: Channel<DownloadProgress>) => __TAURI_INVOKE<string>("download_ffmpeg", { onProgress }),
	listModels: () => __TAURI_INVOKE<ModelMetadata[]>("list_models"),
	getLibtorchStatus: () => __TAURI_INVOKE<LibTorchInfo>("get_libtorch_status"),
	downloadLibtorch: (onProgress: Channel<DownloadProgress>) => __TAURI_INVOKE<string>("download_libtorch", { onProgress }),
	downloadModel: (modelId: string, onProgress: Channel<DownloadProgress>) => __TAURI_INVOKE<string>("download_model", { modelId, onProgress }),
};

/* Types */
export type DownloadProgress = {
	downloaded: number,
	total: number,
};

export type FfmpegInfo = {
	found: boolean,
	path: string | null,
	version: string | null,
	encoders: string[],
	decoders: string[],
};

export type LibTorchBackend = "cpu" | "cuda" | "rocm";

export type LibTorchInfo = {
	backend: LibTorchBackend,
	downloaded: boolean,
	version: string | null,
	driver: string | null,
	devices: string[],
	path: string | null,
};

export type ModelKind = "interpolate" | "upscale" | "denoise" | "decompress" | "deblur";

export type ModelMetadata = {
	id: string,
	kind: ModelKind,
	scale?: number,
	arch: string,
	torch?: string | null,
	ncnn?: string[] | null,
	license?: string | null,
	source_url?: string | null,
	download_url?: string | null,
	sha256?: string | null,
};

export type ProjectEntry = {
	name: string,
	path: string,
};

export type RenderProgress = {
	framesProcessed: number,
	totalFrames: number,
};

export type Settings = {
	language: string,
	theme: string,
};

