//! RIFE v4.6 (`flownet`) — clean burn port, generated from the ncnn graph.
//!
//! Generated by `tools/rife_gen_burn.py` from `ref/rife-v4.6/flownet.param`
//! (nihui/rife-ncnn-vulkan, MIT). Do not hand-edit — regenerate instead.

use burn::module::Module;
use burn::nn::conv::{Conv2d, Conv2dConfig, ConvTranspose2d, ConvTranspose2dConfig};
use burn::nn::PaddingConfig2d;
use burn::tensor::activation::{leaky_relu, sigmoid};
use burn::tensor::backend::Backend;
use burn::tensor::module::interpolate;
use burn::tensor::ops::{InterpolateMode, InterpolateOptions};
use burn::tensor::{Int, Tensor};

use crate::arch::warp::grid_sample;

fn conv2d<B: Backend>(in_c: usize, out_c: usize, stride: usize, device: &B::Device) -> Conv2d<B> {
    Conv2dConfig::new([in_c, out_c], [3, 3])
        .with_stride([stride, stride])
        .with_padding(PaddingConfig2d::Same)
        .init(device)
}

fn deconv2d<B: Backend>(in_c: usize, out_c: usize, device: &B::Device) -> ConvTranspose2d<B> {
    ConvTranspose2dConfig::new([in_c, out_c], [4, 4])
        .with_stride([2, 2])
        .with_padding([1, 1])
        .init(device)
}

/// Channel-axis slice [s..e) (ncnn Crop on axis 0).
fn slice_c<B: Backend>(x: Tensor<B, 4>, s: usize, e: usize) -> Tensor<B, 4> {
    let [n, _c, h, w] = x.dims();
    x.slice([0..n, s..e, 0..h, 0..w])
}

/// Bilinear resize by a scale factor (ncnn Interp, type 2).
fn interp<B: Backend>(x: Tensor<B, 4>, scale: f32) -> Tensor<B, 4> {
    let [_, _, h, w] = x.dims();
    let oh = ((h as f32) * scale).round() as usize;
    let ow = ((w as f32) * scale).round() as usize;
    interpolate(
        x,
        [oh, ow],
        InterpolateOptions::new(InterpolateMode::Bilinear).with_align_corners(false),
    )
}

/// PixelShuffle upscale by 2.
fn pixel_shuffle<B: Backend>(x: Tensor<B, 4>) -> Tensor<B, 4> {
    let [n, c, h, w] = x.dims();
    x.reshape([n, c / 4, 2, 2, h, w])
        .permute([0, 1, 4, 2, 5, 3])
        .reshape([n, c / 4, h * 2, w * 2])
}

/// rife.Warp: backward bilinear warp by a 2-channel flow (align_corners=true,
/// border padding) — matches `warp.comp`.
fn warp<B: Backend>(img: Tensor<B, 4>, flow: Tensor<B, 4>) -> Tensor<B, 4> {
    let [n, _c, h, w] = img.dims();
    let fx = flow.clone().slice([0..n, 0..1, 0..h, 0..w]);
    let fy = flow.slice([0..n, 1..2, 0..h, 0..w]);

    // pixel coordinates 0..W-1 / 0..H-1 broadcast over batch/spatial
    let xs = Tensor::<B, 1, Int>::arange(0..w as i64, &img.device())
        .float()
        .reshape([1, 1, 1, w]);
    let ys = Tensor::<B, 1, Int>::arange(0..h as i64, &img.device())
        .float()
        .reshape([1, 1, h, 1]);

    // sample = coord + flow, normalized to [-1,1] (align_corners=True)
    let sx = (xs + fx) / ((w - 1) as f64 / 2.0) - 1.0;
    let sy = (ys + fy) / ((h - 1) as f64 / 2.0) - 1.0;
    let grid = Tensor::cat(vec![sx.permute([0, 2, 3, 1]), sy.permute([0, 2, 3, 1])], 3);
    grid_sample(img, grid)
}

/// scalar - tensor (ncnn BinaryOp RSUB).
fn sub_r<B: Backend>(x: Tensor<B, 4>, s: f32) -> Tensor<B, 4> {
    Tensor::ones_like(&x) * s - x
}

#[derive(Module, Debug)]
pub struct RifeNet<B: Backend> {
    convrelu_0: Conv2d<B>,
    convrelu_1: Conv2d<B>,
    conv_22: Conv2d<B>,
    conv_23: Conv2d<B>,
    conv_24: Conv2d<B>,
    conv_25: Conv2d<B>,
    conv_26: Conv2d<B>,
    conv_27: Conv2d<B>,
    conv_28: Conv2d<B>,
    conv_29: Conv2d<B>,
    deconv_60: ConvTranspose2d<B>,
    convrelu_2: Conv2d<B>,
    convrelu_3: Conv2d<B>,
    conv_32: Conv2d<B>,
    conv_33: Conv2d<B>,
    conv_34: Conv2d<B>,
    conv_35: Conv2d<B>,
    conv_36: Conv2d<B>,
    conv_37: Conv2d<B>,
    conv_38: Conv2d<B>,
    conv_39: Conv2d<B>,
    deconv_61: ConvTranspose2d<B>,
    convrelu_4: Conv2d<B>,
    convrelu_5: Conv2d<B>,
    conv_42: Conv2d<B>,
    conv_43: Conv2d<B>,
    conv_44: Conv2d<B>,
    conv_45: Conv2d<B>,
    conv_46: Conv2d<B>,
    conv_47: Conv2d<B>,
    conv_48: Conv2d<B>,
    conv_49: Conv2d<B>,
    deconv_62: ConvTranspose2d<B>,
    convrelu_6: Conv2d<B>,
    convrelu_7: Conv2d<B>,
    conv_52: Conv2d<B>,
    conv_53: Conv2d<B>,
    conv_54: Conv2d<B>,
    conv_55: Conv2d<B>,
    conv_56: Conv2d<B>,
    conv_57: Conv2d<B>,
    conv_58: Conv2d<B>,
    conv_59: Conv2d<B>,
    deconv_63: ConvTranspose2d<B>,
}

impl<B: Backend> RifeNet<B> {
    pub fn new(device: &B::Device) -> Self {
        Self {
            convrelu_0: conv2d(7, 96, 2, device),
            convrelu_1: conv2d(96, 192, 2, device),
            conv_22: conv2d(192, 192, 1, device),
            conv_23: conv2d(192, 192, 1, device),
            conv_24: conv2d(192, 192, 1, device),
            conv_25: conv2d(192, 192, 1, device),
            conv_26: conv2d(192, 192, 1, device),
            conv_27: conv2d(192, 192, 1, device),
            conv_28: conv2d(192, 192, 1, device),
            conv_29: conv2d(192, 192, 1, device),
            deconv_60: deconv2d(192, 24, device),
            convrelu_2: conv2d(12, 64, 2, device),
            convrelu_3: conv2d(64, 128, 2, device),
            conv_32: conv2d(128, 128, 1, device),
            conv_33: conv2d(128, 128, 1, device),
            conv_34: conv2d(128, 128, 1, device),
            conv_35: conv2d(128, 128, 1, device),
            conv_36: conv2d(128, 128, 1, device),
            conv_37: conv2d(128, 128, 1, device),
            conv_38: conv2d(128, 128, 1, device),
            conv_39: conv2d(128, 128, 1, device),
            deconv_61: deconv2d(128, 24, device),
            convrelu_4: conv2d(12, 48, 2, device),
            convrelu_5: conv2d(48, 96, 2, device),
            conv_42: conv2d(96, 96, 1, device),
            conv_43: conv2d(96, 96, 1, device),
            conv_44: conv2d(96, 96, 1, device),
            conv_45: conv2d(96, 96, 1, device),
            conv_46: conv2d(96, 96, 1, device),
            conv_47: conv2d(96, 96, 1, device),
            conv_48: conv2d(96, 96, 1, device),
            conv_49: conv2d(96, 96, 1, device),
            deconv_62: deconv2d(96, 24, device),
            convrelu_6: conv2d(12, 32, 2, device),
            convrelu_7: conv2d(32, 64, 2, device),
            conv_52: conv2d(64, 64, 1, device),
            conv_53: conv2d(64, 64, 1, device),
            conv_54: conv2d(64, 64, 1, device),
            conv_55: conv2d(64, 64, 1, device),
            conv_56: conv2d(64, 64, 1, device),
            conv_57: conv2d(64, 64, 1, device),
            conv_58: conv2d(64, 64, 1, device),
            conv_59: conv2d(64, 64, 1, device),
            deconv_63: deconv2d(64, 24, device),
        }
    }

    /// Interpolate frame `in0` -> `in1` at `in2` (timestep in [0,1]).
    pub fn forward(&self, in0: Tensor<B, 4>, in1: Tensor<B, 4>, in2: Tensor<B, 4>) -> Tensor<B, 4> {
        let b_in0 = in0;
        let b_1 = b_in0.clone();
        let b_2 = b_in0.clone();
        let b_3 = b_in0.clone();
        let b_4 = b_in0.clone();
        let b_5 = b_in0;
        let b_in1 = in1;
        let b_7 = b_in1.clone();
        let b_8 = b_in1.clone();
        let b_9 = b_in1.clone();
        let b_10 = b_in1.clone();
        let b_11 = b_in1;
        let b_in2 = in2;
        let b_13 = b_in2.clone();
        let b_14 = b_in2.clone();
        let b_15 = b_in2.clone();
        let b_16 = b_in2;
        let b_17 = Tensor::cat(vec![b_1, b_7, b_13], 1);
        let b_18 = interp(b_17, 1.250000e-01);
        let b_20 = leaky_relu(self.convrelu_0.forward(b_18), 0.2);
        let b_21 = leaky_relu(self.convrelu_1.forward(b_20), 0.2);
        let b_22 = b_21.clone();
        let b_23 = b_21;
        let b_25 = self.conv_22.forward(b_23);
        let b_26 = b_25 + b_22;
        let b_28 = leaky_relu(b_26, 2.000000e-01);
        let b_29 = b_28.clone();
        let b_30 = b_28;
        let b_32 = self.conv_23.forward(b_30);
        let b_33 = b_32 + b_29;
        let b_35 = leaky_relu(b_33, 2.000000e-01);
        let b_36 = b_35.clone();
        let b_37 = b_35;
        let b_39 = self.conv_24.forward(b_37);
        let b_40 = b_39 + b_36;
        let b_42 = leaky_relu(b_40, 2.000000e-01);
        let b_43 = b_42.clone();
        let b_44 = b_42;
        let b_46 = self.conv_25.forward(b_44);
        let b_47 = b_46 + b_43;
        let b_49 = leaky_relu(b_47, 2.000000e-01);
        let b_50 = b_49.clone();
        let b_51 = b_49;
        let b_53 = self.conv_26.forward(b_51);
        let b_54 = b_53 + b_50;
        let b_56 = leaky_relu(b_54, 2.000000e-01);
        let b_57 = b_56.clone();
        let b_58 = b_56;
        let b_60 = self.conv_27.forward(b_58);
        let b_61 = b_60 + b_57;
        let b_63 = leaky_relu(b_61, 2.000000e-01);
        let b_64 = b_63.clone();
        let b_65 = b_63;
        let b_67 = self.conv_28.forward(b_65);
        let b_68 = b_67 + b_64;
        let b_70 = leaky_relu(b_68, 2.000000e-01);
        let b_71 = b_70.clone();
        let b_72 = b_70;
        let b_74 = self.conv_29.forward(b_72);
        let b_75 = b_74 + b_71;
        let b_76 = leaky_relu(b_75, 2.000000e-01);
        let b_77 = self.deconv_60.forward(b_76);
        let b_flow0 = pixel_shuffle(b_77);
        let b_79 = interp(b_flow0, 8.000000e+00);
        let b_80 = b_79.clone();
        let b_81 = b_79;
        let b_82 = slice_c(b_81, 0, 4);
        let b_83 = b_82 * 8.000000e+00;
        let b_84 = b_83.clone();
        let b_85 = b_83.clone();
        let b_86 = b_83.clone();
        let b_87 = b_83;
        let b_88 = interp(b_85, 2.500000e-01);
        let b_89 = b_88 / 4.000000e+00;
        let b_90 = slice_c(b_87, 2, 4);
        let b_91 = warp(b_11, b_90);
        let b_92 = slice_c(b_86, 0, 2);
        let b_93 = warp(b_5, b_92);
        let b_94 = slice_c(b_80, 4, 5);
        let b_95 = b_94.clone();
        let b_96 = b_94;
        let b_97 = Tensor::cat(vec![b_93, b_91, b_14, b_95], 1);
        let b_98 = interp(b_97, 2.500000e-01);
        let b_99 = Tensor::cat(vec![b_98, b_89], 1);
        let b_101 = leaky_relu(self.convrelu_2.forward(b_99), 0.2);
        let b_102 = leaky_relu(self.convrelu_3.forward(b_101), 0.2);
        let b_103 = b_102.clone();
        let b_104 = b_102;
        let b_106 = self.conv_32.forward(b_104);
        let b_107 = b_106 + b_103;
        let b_109 = leaky_relu(b_107, 2.000000e-01);
        let b_110 = b_109.clone();
        let b_111 = b_109;
        let b_113 = self.conv_33.forward(b_111);
        let b_114 = b_113 + b_110;
        let b_116 = leaky_relu(b_114, 2.000000e-01);
        let b_117 = b_116.clone();
        let b_118 = b_116;
        let b_120 = self.conv_34.forward(b_118);
        let b_121 = b_120 + b_117;
        let b_123 = leaky_relu(b_121, 2.000000e-01);
        let b_124 = b_123.clone();
        let b_125 = b_123;
        let b_127 = self.conv_35.forward(b_125);
        let b_128 = b_127 + b_124;
        let b_130 = leaky_relu(b_128, 2.000000e-01);
        let b_131 = b_130.clone();
        let b_132 = b_130;
        let b_134 = self.conv_36.forward(b_132);
        let b_135 = b_134 + b_131;
        let b_137 = leaky_relu(b_135, 2.000000e-01);
        let b_138 = b_137.clone();
        let b_139 = b_137;
        let b_141 = self.conv_37.forward(b_139);
        let b_142 = b_141 + b_138;
        let b_144 = leaky_relu(b_142, 2.000000e-01);
        let b_145 = b_144.clone();
        let b_146 = b_144;
        let b_148 = self.conv_38.forward(b_146);
        let b_149 = b_148 + b_145;
        let b_151 = leaky_relu(b_149, 2.000000e-01);
        let b_152 = b_151.clone();
        let b_153 = b_151;
        let b_155 = self.conv_39.forward(b_153);
        let b_156 = b_155 + b_152;
        let b_157 = leaky_relu(b_156, 2.000000e-01);
        let b_158 = self.deconv_61.forward(b_157);
        let b_flow1 = pixel_shuffle(b_158);
        let b_160 = interp(b_flow1, 4.000000e+00);
        let b_161 = b_160.clone();
        let b_162 = b_160;
        let b_163 = slice_c(b_162, 0, 4);
        let b_164 = b_84 * 1.0 + b_163 * 4.0;
        let b_165 = b_164.clone();
        let b_166 = b_164.clone();
        let b_167 = b_164.clone();
        let b_168 = b_164;
        let b_169 = slice_c(b_161, 4, 5);
        let b_170 = b_96 + b_169;
        let b_171 = b_170.clone();
        let b_172 = b_170;
        let b_173 = interp(b_166, 5.000000e-01);
        let b_174 = b_173 / 2.000000e+00;
        let b_175 = slice_c(b_168, 2, 4);
        let b_176 = warp(b_10, b_175);
        let b_177 = slice_c(b_167, 0, 2);
        let b_178 = warp(b_4, b_177);
        let b_179 = Tensor::cat(vec![b_178, b_176, b_15, b_171], 1);
        let b_180 = interp(b_179, 5.000000e-01);
        let b_181 = Tensor::cat(vec![b_180, b_174], 1);
        let b_183 = leaky_relu(self.convrelu_4.forward(b_181), 0.2);
        let b_184 = leaky_relu(self.convrelu_5.forward(b_183), 0.2);
        let b_185 = b_184.clone();
        let b_186 = b_184;
        let b_188 = self.conv_42.forward(b_186);
        let b_189 = b_188 + b_185;
        let b_191 = leaky_relu(b_189, 2.000000e-01);
        let b_192 = b_191.clone();
        let b_193 = b_191;
        let b_195 = self.conv_43.forward(b_193);
        let b_196 = b_195 + b_192;
        let b_198 = leaky_relu(b_196, 2.000000e-01);
        let b_199 = b_198.clone();
        let b_200 = b_198;
        let b_202 = self.conv_44.forward(b_200);
        let b_203 = b_202 + b_199;
        let b_205 = leaky_relu(b_203, 2.000000e-01);
        let b_206 = b_205.clone();
        let b_207 = b_205;
        let b_209 = self.conv_45.forward(b_207);
        let b_210 = b_209 + b_206;
        let b_212 = leaky_relu(b_210, 2.000000e-01);
        let b_213 = b_212.clone();
        let b_214 = b_212;
        let b_216 = self.conv_46.forward(b_214);
        let b_217 = b_216 + b_213;
        let b_219 = leaky_relu(b_217, 2.000000e-01);
        let b_220 = b_219.clone();
        let b_221 = b_219;
        let b_223 = self.conv_47.forward(b_221);
        let b_224 = b_223 + b_220;
        let b_226 = leaky_relu(b_224, 2.000000e-01);
        let b_227 = b_226.clone();
        let b_228 = b_226;
        let b_230 = self.conv_48.forward(b_228);
        let b_231 = b_230 + b_227;
        let b_233 = leaky_relu(b_231, 2.000000e-01);
        let b_234 = b_233.clone();
        let b_235 = b_233;
        let b_237 = self.conv_49.forward(b_235);
        let b_238 = b_237 + b_234;
        let b_239 = leaky_relu(b_238, 2.000000e-01);
        let b_240 = self.deconv_62.forward(b_239);
        let b_flow2 = pixel_shuffle(b_240);
        let b_242 = interp(b_flow2, 2.000000e+00);
        let b_243 = b_242.clone();
        let b_244 = b_242;
        let b_245 = slice_c(b_244, 0, 4);
        let b_246 = b_165 * 1.0 + b_245 * 2.0;
        let b_247 = b_246.clone();
        let b_261 = b_246.clone();
        let b_249 = b_246.clone();
        let b_250 = b_246;
        let b_251 = slice_c(b_243, 4, 5);
        let b_252 = b_172 + b_251;
        let b_253 = b_252.clone();
        let b_254 = b_252;
        let b_255 = slice_c(b_250, 2, 4);
        let b_256 = warp(b_9, b_255);
        let b_257 = slice_c(b_249, 0, 2);
        let b_258 = warp(b_3, b_257);
        let b_260 = Tensor::cat(vec![b_258, b_256, b_16, b_253], 1);
        let b_262 = Tensor::cat(vec![b_260, b_261], 1);
        let b_264 = leaky_relu(self.convrelu_6.forward(b_262), 0.2);
        let b_265 = leaky_relu(self.convrelu_7.forward(b_264), 0.2);
        let b_266 = b_265.clone();
        let b_267 = b_265;
        let b_269 = self.conv_52.forward(b_267);
        let b_270 = b_269 + b_266;
        let b_272 = leaky_relu(b_270, 2.000000e-01);
        let b_273 = b_272.clone();
        let b_274 = b_272;
        let b_276 = self.conv_53.forward(b_274);
        let b_277 = b_276 + b_273;
        let b_279 = leaky_relu(b_277, 2.000000e-01);
        let b_280 = b_279.clone();
        let b_281 = b_279;
        let b_283 = self.conv_54.forward(b_281);
        let b_284 = b_283 + b_280;
        let b_286 = leaky_relu(b_284, 2.000000e-01);
        let b_287 = b_286.clone();
        let b_288 = b_286;
        let b_290 = self.conv_55.forward(b_288);
        let b_291 = b_290 + b_287;
        let b_293 = leaky_relu(b_291, 2.000000e-01);
        let b_294 = b_293.clone();
        let b_295 = b_293;
        let b_297 = self.conv_56.forward(b_295);
        let b_298 = b_297 + b_294;
        let b_300 = leaky_relu(b_298, 2.000000e-01);
        let b_301 = b_300.clone();
        let b_302 = b_300;
        let b_304 = self.conv_57.forward(b_302);
        let b_305 = b_304 + b_301;
        let b_307 = leaky_relu(b_305, 2.000000e-01);
        let b_308 = b_307.clone();
        let b_309 = b_307;
        let b_311 = self.conv_58.forward(b_309);
        let b_312 = b_311 + b_308;
        let b_314 = leaky_relu(b_312, 2.000000e-01);
        let b_315 = b_314.clone();
        let b_316 = b_314;
        let b_318 = self.conv_59.forward(b_316);
        let b_319 = b_318 + b_315;
        let b_320 = leaky_relu(b_319, 2.000000e-01);
        let b_321 = self.deconv_63.forward(b_320);
        let b_flow3 = pixel_shuffle(b_321);
        let b_324 = b_flow3.clone();
        let b_325 = b_flow3;
        let b_326 = slice_c(b_325, 0, 4);
        let b_327 = b_247 + b_326;
        let b_328 = b_327.clone();
        let b_329 = b_327;
        let b_330 = slice_c(b_324, 4, 5);
        let b_331 = b_254 + b_330;
        let b_332 = sigmoid(b_331);
        let b_333 = b_332.clone();
        let b_334 = b_332;
        let b_335 = sub_r(b_333, 1.000000e+00);
        let b_336 = slice_c(b_328, 2, 4);
        let b_337 = warp(b_8, b_336);
        let b_338 = b_337 * b_335;
        let b_339 = slice_c(b_329, 0, 2);
        let b_340 = warp(b_2, b_339);
        let b_341 = b_340 * b_334;
        let b_out0 = b_341 + b_338;
        b_out0
    }

    /// Load weights from the rife-v4.6 ncnn `flownet.bin`.
    ///
    /// Format (per weighted layer, in .param order):
    /// `[tag u32 = 0x01306B47][weights wsize x f16][bias out x f32 if bias_term]`
    pub fn load_from_ncnn(&mut self, bin: &[u8], device: &B::Device) -> Result<(), String> {
        use burn::module::Param;
        use burn::tensor::{f16, TensorData};
        let mut pos = 0usize;
        let mut rd = |out: usize,
                      wsize: usize,
                      in_c: usize,
                      k: usize,
                      bias: bool,
                      transpose: bool|
         -> (Tensor<B, 4>, Option<Tensor<B, 1>>) {
            pos += 4; // fp16 tag
            let w: Vec<f32> = (0..wsize)
                .map(|i| {
                    f16::from_bits(u16::from_le_bytes([bin[pos + 2 * i], bin[pos + 2 * i + 1]]))
                        .to_f32()
                })
                .collect();
            pos += 2 * wsize;
            let b = if bias {
                let bv: Vec<f32> = (0..out)
                    .map(|i| {
                        f32::from_le_bytes([
                            bin[pos + 4 * i],
                            bin[pos + 4 * i + 1],
                            bin[pos + 4 * i + 2],
                            bin[pos + 4 * i + 3],
                        ])
                    })
                    .collect();
                pos += 4 * out;
                Some(Tensor::from_data(TensorData::new(bv, [out]), device))
            } else {
                None
            };
            // ncnn stores deconv weights out-major [out, in, k, k]; burn's
            // ConvTranspose2d expects [in, out, k, k].
            let wt = Tensor::from_data(TensorData::new(w, [out, in_c, k, k]), device);
            let wt = if transpose {
                wt.permute([1, 0, 2, 3])
            } else {
                wt
            };
            (wt, b)
        };
        let (w, b) = rd(96, 6048, 7, 3, true, false);
        self.convrelu_0.weight = Param::from_tensor(w);
        self.convrelu_0.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 165888, 96, 3, true, false);
        self.convrelu_1.weight = Param::from_tensor(w);
        self.convrelu_1.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_22.weight = Param::from_tensor(w);
        self.conv_22.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_23.weight = Param::from_tensor(w);
        self.conv_23.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_24.weight = Param::from_tensor(w);
        self.conv_24.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_25.weight = Param::from_tensor(w);
        self.conv_25.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_26.weight = Param::from_tensor(w);
        self.conv_26.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_27.weight = Param::from_tensor(w);
        self.conv_27.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_28.weight = Param::from_tensor(w);
        self.conv_28.bias = b.map(Param::from_tensor);
        let (w, b) = rd(192, 331776, 192, 3, true, false);
        self.conv_29.weight = Param::from_tensor(w);
        self.conv_29.bias = b.map(Param::from_tensor);
        let (w, b) = rd(24, 73728, 192, 4, true, true);
        self.deconv_60.weight = Param::from_tensor(w);
        self.deconv_60.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 6912, 12, 3, true, false);
        self.convrelu_2.weight = Param::from_tensor(w);
        self.convrelu_2.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 73728, 64, 3, true, false);
        self.convrelu_3.weight = Param::from_tensor(w);
        self.convrelu_3.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_32.weight = Param::from_tensor(w);
        self.conv_32.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_33.weight = Param::from_tensor(w);
        self.conv_33.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_34.weight = Param::from_tensor(w);
        self.conv_34.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_35.weight = Param::from_tensor(w);
        self.conv_35.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_36.weight = Param::from_tensor(w);
        self.conv_36.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_37.weight = Param::from_tensor(w);
        self.conv_37.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_38.weight = Param::from_tensor(w);
        self.conv_38.bias = b.map(Param::from_tensor);
        let (w, b) = rd(128, 147456, 128, 3, true, false);
        self.conv_39.weight = Param::from_tensor(w);
        self.conv_39.bias = b.map(Param::from_tensor);
        let (w, b) = rd(24, 49152, 128, 4, true, true);
        self.deconv_61.weight = Param::from_tensor(w);
        self.deconv_61.bias = b.map(Param::from_tensor);
        let (w, b) = rd(48, 5184, 12, 3, true, false);
        self.convrelu_4.weight = Param::from_tensor(w);
        self.convrelu_4.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 41472, 48, 3, true, false);
        self.convrelu_5.weight = Param::from_tensor(w);
        self.convrelu_5.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_42.weight = Param::from_tensor(w);
        self.conv_42.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_43.weight = Param::from_tensor(w);
        self.conv_43.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_44.weight = Param::from_tensor(w);
        self.conv_44.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_45.weight = Param::from_tensor(w);
        self.conv_45.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_46.weight = Param::from_tensor(w);
        self.conv_46.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_47.weight = Param::from_tensor(w);
        self.conv_47.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_48.weight = Param::from_tensor(w);
        self.conv_48.bias = b.map(Param::from_tensor);
        let (w, b) = rd(96, 82944, 96, 3, true, false);
        self.conv_49.weight = Param::from_tensor(w);
        self.conv_49.bias = b.map(Param::from_tensor);
        let (w, b) = rd(24, 36864, 96, 4, true, true);
        self.deconv_62.weight = Param::from_tensor(w);
        self.deconv_62.bias = b.map(Param::from_tensor);
        let (w, b) = rd(32, 3456, 12, 3, true, false);
        self.convrelu_6.weight = Param::from_tensor(w);
        self.convrelu_6.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 18432, 32, 3, true, false);
        self.convrelu_7.weight = Param::from_tensor(w);
        self.convrelu_7.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_52.weight = Param::from_tensor(w);
        self.conv_52.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_53.weight = Param::from_tensor(w);
        self.conv_53.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_54.weight = Param::from_tensor(w);
        self.conv_54.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_55.weight = Param::from_tensor(w);
        self.conv_55.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_56.weight = Param::from_tensor(w);
        self.conv_56.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_57.weight = Param::from_tensor(w);
        self.conv_57.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_58.weight = Param::from_tensor(w);
        self.conv_58.bias = b.map(Param::from_tensor);
        let (w, b) = rd(64, 36864, 64, 3, true, false);
        self.conv_59.weight = Param::from_tensor(w);
        self.conv_59.bias = b.map(Param::from_tensor);
        let (w, b) = rd(24, 24576, 64, 4, true, true);
        self.deconv_63.weight = Param::from_tensor(w);
        self.deconv_63.bias = b.map(Param::from_tensor);
        if pos != bin.len() {
            return Err(format!("ncnn bin: consumed {pos} of {} bytes", bin.len()));
        }
        Ok(())
    }
}

#[cfg(all(test, feature = "burn"))]
mod tests {
    use super::*;
    use burn::tensor::TensorData;

    /// Structural check: the graph runs end-to-end and preserves resolution.
    /// Weights are random (unloaded), so this validates shapes/wiring only.
    #[test]
    #[ignore = "requires Vulkan"]
    fn rife_net_forward_preserves_shape() {
        use crate::BurnBackend;
        use burn_wgpu::WgpuDevice;
        let device = WgpuDevice::DiscreteGpu(0);
        let net = RifeNet::<BurnBackend<f32>>::new(&device);
        let in0 = Tensor::<BurnBackend<f32>, 4>::from_data(
            TensorData::new(vec![0.5f32; 3 * 64 * 64], [1, 3, 64, 64]),
            &device,
        );
        let in1 = Tensor::<BurnBackend<f32>, 4>::from_data(
            TensorData::new(vec![0.6f32; 3 * 64 * 64], [1, 3, 64, 64]),
            &device,
        );
        let t = Tensor::<BurnBackend<f32>, 4>::from_data(
            TensorData::new(vec![0.5f32; 64 * 64], [1, 1, 64, 64]),
            &device,
        );
        let out = net.forward(in0, in1, t);
        assert_eq!(out.dims(), [1, 3, 64, 64]);
        let v: Vec<f32> = out.into_data().convert::<f32>().to_vec().unwrap();
        assert!(v.iter().all(|x| x.is_finite()));
    }
}
